### ISSUE TITLE
Documentation-only builds shouldn't fail because of missing dependencies

### ISSUE THREAD

**Issue by kornelski** [crate-ci/meta#13]
https://github.com/onur/docs.rs/issues/147 (it's not exactly CI, but in the family of "the build fails on someone else's headless computer")

`cargo doc` runs a full build, and fails if any `build.rs` script fails. This is a problem for docs.rs, because it can't build documentation for `-sys` crates that usually require a specific library installed on the system (e.g. [ffmpeg-sys won't build](https://docs.rs/ffmpeg-sys/3.4.1/ffmpeg_sys/) without a specific version of ffmpeg, so it doesn't get documented).

At very least there should be some `cfg(doc)` or env variable to detect docs build, so that tricky bits not relevant to the documentation can be skipped. Maybe Cargo/rustdoc could be instructed to plow through build failures and document as much as it can?

**Comment by epage** [comment]
Let me see what can be turned into something tangible for crate-ci org to work on for this.  Our focus is more on streamlining crate management through documentation, tooling, and advocating for fixing problems.

This sounds like a problem within existing tooling and you've opened a related issue with the respective tool.  So is this more seeking to raise awareness for getting help advocating for your problem?

**Comment by kornelski** [comment]
OK, that's probably out of scope.
