### ISSUE TITLE
Recommend Travis CI over AppVeyor now that Windows support is out

### ISSUE THREAD

**Issue by chippers** [crate-ci/meta#25]
[This reddit thread prompted me to think about this](https://www.reddit.com/r/rust/comments/9ndo5k/travis_ci_now_supports_testing_windows_includes/).  Now that Travis CI supports Windows builds, we may want to recommend going to Travis CI over AppVeyor.  I don't think AppVeyor should be removed outright as we don't know the limitations of the Travis CI Windows support yet, or ease of using Windows libs.

Recommending Travis over AppVeyor lowers 3rd party dependencies to a single service by default.  Additionally there seem to be many gripes with AppVeyor support anyways - as per the reddit thread.

> epage
> Other problems with Appveyor
> * The project is tied to the user and not the github org. I have builds for projects that I can't modify, cancel, etc
> * Builds are serial rather than parallel
> * No scheduled builds unless you get permission. This is mostly useful to do once a month or so to ensure external factors haven't killed your build.

**Comment by epage** [comment]
Agreed, Appveyor has enough problems to make recommending Travis worthwhile.

**Comment by ratmice** [comment]
I don't think it is wise to recommend windows on travis, certainly not without caveats that it may now leak secrets.
https://github.com/travis-ci/travis-build/pull/1719

**Comment by epage** [comment]
I'm actually interested in Azure Pipelines replacing both.  We've [started looking into it](https://github.com/crate-ci/resources/issues), including creating templates.  It seems updating the Rust plugin is the right way and I'm [waiting on it being done](https://github.com/crate-ci/resources/issues/2) before migrating some projects as an experiment before fully switching over.
