### ISSUE TITLE
Recommendation for CI cron setting

### ISSUE THREAD

**Issue by epage** [crate-ci/meta#7]
The following sources of change exist in a project
- PRs
- rust channels
- dependencies

Setting up a cron schedule for a CI helps to verify a project for the latter two but there is a tension here between 
- Minimizing impact on PRs / clients
- Minimizing the load on the free CI services we use

## Proposal

Project with nightly features: frequently, at most once a day

High throughput projects: Let it fail

Low throughput projects: Schedule a monthly cron job (`0 0 1 * *`)
- From experience, dependencies and nightly so rarely break a crate that a probabilistic approach seems reasonable

## Alternatives

So different approaches that can be taken for nightly
1. Allow failures on nightly.  I assume the PR is never told, so someone has to go to travis to notice
2. Daily cron job (frequency of nightly releases)
3. Let it fail, assuming nightly fails so rarely that it won't ever be a problem
4. Lock down to specific versions, ideally with a tool to automatically create PRs to update

And for dependencies
1. Exact version can cause a lot of duplicated code for the end product
2. Submit lock file.  This helps your process but doesn't help your clients
3. Submit a lock file and have a bot that creates / submits PRs to update it

**Comment by epage** [comment]
Note: appveyor has scheduled builds [disabled by default](https://www.appveyor.com/blog/2017/11/08/sheduled-builds-for-free-accounts/) and you need to contact them to get them enabled.

Maybe as part of minimizing CI load, we only really need scheduled builds for one CI service?

But that might help contribute to the problem that led to [rust 1.24.1](https://blog.rust-lang.org/2018/03/01/Rust-1.24.1.html).

**Comment by CAD97** [comment]
What I've done in the past:

- Projects using nightly features: run daily Travis cron jobs if no other build in the last 24h.
- Projects using no nightly features: no cron job.

It's a highly project-specific decision, though, I think. If you are using nightly features, though, you want to be notified when something breaks. [I've caught at least one rust bug that way.](https://github.com/rust-lang/rust/issues/46976)

If you allow_failure for your nightly build, then yes, no notification will (by default) happen even if it fails. If you do that, there is _no point_ to a nightly cron job, and you should be using one that lines up closer to the Rust release cadence.

**Comment by epage** [comment]
Good call on whether the project is using nightly or not! I've been able to avoid nightly-only features myself so it never crossed my mind.

> If you allow_failure for your nightly build, then yes, no notification will (by default) happen even if it fails. If you do that, there is no point to a nightly cron job, and you should be using one that lines up closer to the Rust release cadence.

To be clear, I view the "allow_failure" solution as an alternative to configuring cron.  I agree that there isn't as much value in that case.

> It's a highly project-specific decision, though

Agreed but hopefully with some basic guidelines with rationale, it'll provide a default solution until someone finds a corner case to do something differently that hopfully will be helpful for people new to the ecosystem.

**Comment by nastevens** [comment]
I agree with @CAD97's recommendations, except for that even projects that don't use nightly features can benefit from an occasional CI build for a couple of reasons:

* The CI providers themselves are software - it's possible (if unlikely) that a CI provider introduces platform changes that impact your build
* There is a positive perception when a new developer comes to a library and sees a recent successful CI build - seeing that CI hasn't run for 6 months is off-putting.

Based on the above, I think for projects not using nightly features there is still benefit in an occasional cron job - weekly or monthly probably makes sense. I actually just backed off some of my repos that don't use nightly features from building every night because I realized I am just causing unnecessary load. Weekly feels right to me, but I don't have any empirical justification to pick weekly over monthly or v.v.

**Comment by epage** [comment]
> There is a positive perception when a new developer comes to a library and sees a recent successful CI build - seeing that CI hasn't run for 6 months is off-putting.

I've actually never noticed.  I only noticed if the CI is broken and after having worked through a lot of failures from tooling in Rust, Travis, and Appveyor, I'm not more forgiving of it.  Having to figure out how to minimize those failures was one of my motivations for starting this.
